structure(list(url = "http://www.colourlovers.com/api/pattern/1451?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:33:35 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "790", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:33:35 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "790", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<patterns numResults=\"1\" totalResults=\"5794619\">\n\t<pattern>\n\t\t<id>1451</id>\n\t\t<title><![CDATA[Geek Chic]]></title>\n\t\t<userName><![CDATA[_183]]></userName>\n\t\t<numViews>676</numViews>\n\t\t<numVotes>3</numVotes>\n\t\t<numComments>2</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2007-12-09 15:36:03</dateCreated>\n\t\t<colors>\n\t\t\t<hex>52202E</hex>\n\t\t\t<hex>1A1313</hex>\n\t\t\t<hex>F7F6A8</hex>\n\t\t\t<hex>C4F04D</hex>\n\t\t</colors>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/palette/2285499/Nestled\" target=\"_blank\"><img src=\"http://www.colourlovers.com/images/badges/pw/2285/2285499_Nestled.png\" style=\"width: 240px; height: 120px; border: 0 none;\" alt=\"Nestled\" /></a>\r\n<div style=\"width: 300px; text-align: center;\"><a href=\"http://www.colourlovers.com/contests/moo/minicard/2285499\" target=\"_blank\" style=\"display: block; margin-bottom: 5px; width: 300px; height: 120px; -moz-box-shadow: 0 1px 4px #d1d1d1; -webkit-box-shadow: 0 1px 4px #d1d1d1; box-shadow: 0 1px 4px #d1d1d1; filter: progid:DXImageTransform.Microsoft.Shadow(Strength=1, Direction=180, Color=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/pattern/1451/Geek_Chic]]></url>\n\t\t<imageUrl><![CDATA[http://static.colourlovers.com/images/patterns/1/1451.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/n/1/1451_Geek_Chic.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/pattern/1451</apiUrl>\n\t\t<template>\n\t\t\t<title><![CDATA[Argyle]]></title>\n\t\t\t<url><![CDATA[http://www.colourlovers.com/pattern/template/7/Argyle]]></url>\n\t\t\t<author>\n\t\t\t\t<userName><![CDATA[COLOURlover]]></userName>\n\t\t\t\t<url><![CDATA[http://www.colourlovers.com/lover/COLOURlover]]></url>\n\t\t\t</author>\n\t\t</template>\n\t</pattern>\n</patterns>"), 
    date = structure(1556645615, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000023, 
    connect = 0.129226, pretransfer = 0.1293, starttransfer = 0.283363, 
    total = 0.283423)), class = "response")
