structure(list(url = "http://www.colourlovers.com/api/pattern/5789044?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:33:53 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "552", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:33:53 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "552", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<patterns numResults=\"1\" totalResults=\"5794619\">\n\t<pattern>\n\t\t<id>5789044</id>\n\t\t<title><![CDATA[#013 Cold Blueberry]]></title>\n\t\t<userName><![CDATA[0.2]]></userName>\n\t\t<numViews>13</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-08 06:07:59</dateCreated>\n\t\t<colors>\n\t\t\t<hex>FFFFFF</hex>\n\t\t\t<hex>00FFFF</hex>\n\t\t\t<hex>4C2C00</hex>\n\t\t\t<hex>0000FF</hex>\n\t\t\t<hex>FFFFFF</hex>\n\t\t</colors>\n\t\t<description><![CDATA[Or berry blue if you like it the other way round.]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/pattern/5789044/013_Cold_Blueberry]]></url>\n\t\t<imageUrl><![CDATA[http://static.colourlovers.com/images/patterns/5789/5789044.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/n/5789/5789044_013_Cold_Blueberry.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/pattern/5789044</apiUrl>\n\t\t<template>\n\t\t\t<title><![CDATA[Ice Cream Pops]]></title>\n\t\t\t<url><![CDATA[http://www.colourlovers.com/pattern/template/211769/Ice_Cream_Pops]]></url>\n\t\t\t<author>\n\t\t\t\t<userName><![CDATA[wondercake]]></userName>\n\t\t\t\t<url><![CDATA[http://www.colourlovers.com/lover/wondercake]]></url>\n\t\t\t</author>\n\t\t</template>\n\t</pattern>\n</patterns>"), 
    date = structure(1556645633, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000026, 
    connect = 0.127837, pretransfer = 0.127922, starttransfer = 0.266172, 
    total = 0.266338)), class = "response")
