structure(list(url = "http://www.colourlovers.com/api/pattern/5794648?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 20:26:34 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "515", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 20:26:34 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "515", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<patterns numResults=\"1\" totalResults=\"5794650\">\n\t<pattern>\n\t\t<id>5794648</id>\n\t\t<title><![CDATA[ath pattern 1]]></title>\n\t\t<userName><![CDATA[andrewheiss]]></userName>\n\t\t<numViews>5</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-30 22:21:26</dateCreated>\n\t\t<colors>\n\t\t\t<hex>CCCCCC</hex>\n\t\t\t<hex>E07373</hex>\n\t\t\t<hex>F43F3F</hex>\n\t\t\t<hex>333333</hex>\n\t\t\t<hex>B4B37E</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/pattern/5794648/ath_pattern_1]]></url>\n\t\t<imageUrl><![CDATA[http://static.colourlovers.com/images/patterns/5794/5794648.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/n/5794/5794648_ath_pattern_1.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/pattern/5794648</apiUrl>\n\t\t<template>\n\t\t\t<title><![CDATA[Super Plaid]]></title>\n\t\t\t<url><![CDATA[http://www.colourlovers.com/pattern/template/1/Super_Plaid]]></url>\n\t\t\t<author>\n\t\t\t\t<userName><![CDATA[COLOURlover]]></userName>\n\t\t\t\t<url><![CDATA[http://www.colourlovers.com/lover/COLOURlover]]></url>\n\t\t\t</author>\n\t\t</template>\n\t</pattern>\n</patterns>"), 
    date = structure(1556655994, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 1.8e-05, 
    connect = 0.221952, pretransfer = 0.222051, starttransfer = 0.428438, 
    total = 0.428581)), class = "response")
