structure(list(url = "http://www.colourlovers.com/api/colors/new?format=xml&keywordExact=0&numResults=1", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 03:55:57 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "466", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 03:55:57 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "466", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"9990216\">\n\t<color>\n\t\t<id>9990216</id>\n\t\t<title><![CDATA[♥]]></title>\n\t\t<userName><![CDATA[MistyAamen]]></userName>\n\t\t<numViews>0</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-29 22:47:58</dateCreated>\n\t\t<hex>C082F0</hex>\n\t\t<rgb>\n\t\t\t<red>192</red>\n\t\t\t<green>130</green>\n\t\t\t<blue>240</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>274</hue>\n\t\t\t<saturation>46</saturation>\n\t\t\t<value>94</value>\n\t\t</hsv>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/C082F0/♥]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/C082F0/100/100/♥.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/9990/9990216_.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/C082F0</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556596557, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.00003, 
    connect = 0.194451, pretransfer = 0.194549, starttransfer = 0.365218, 
    total = 0.365345)), class = "response")
