structure(list(url = "http://www.colourlovers.com/api/colors/new?format=xml&numResults=1", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 05:44:30 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "476", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 05:44:30 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "476", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"9990269\">\n\t<color>\n\t\t<id>9990269</id>\n\t\t<title><![CDATA[Loosely Limed]]></title>\n\t\t<userName><![CDATA[MistyAamen]]></userName>\n\t\t<numViews>4</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-30 00:41:06</dateCreated>\n\t\t<hex>97DD4B</hex>\n\t\t<rgb>\n\t\t\t<red>151</red>\n\t\t\t<green>221</green>\n\t\t\t<blue>75</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>89</hue>\n\t\t\t<saturation>66</saturation>\n\t\t\t<value>87</value>\n\t\t</hsv>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/97DD4B/Loosely_Limed]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/97DD4B/100/100/Loosely_Limed.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/9990/9990269_Loosely_Limed.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/97DD4B</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556603070, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000041, 
    connect = 0.146784, pretransfer = 0.14697, starttransfer = 0.339347, 
    total = 0.33947)), class = "response")
