structure(list(url = "http://www.colourlovers.com/api/colors/new?format=xml&numResults=2", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 04:17:38 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "554", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 04:17:38 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "554", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"2\" totalResults=\"9990224\">\n\t<color>\n\t\t<id>9990224</id>\n\t\t<title><![CDATA[early summer leaves]]></title>\n\t\t<userName><![CDATA[driver22]]></userName>\n\t\t<numViews>0</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-29 23:16:27</dateCreated>\n\t\t<hex>03A224</hex>\n\t\t<rgb>\n\t\t\t<red>3</red>\n\t\t\t<green>162</green>\n\t\t\t<blue>36</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>132</hue>\n\t\t\t<saturation>98</saturation>\n\t\t\t<value>64</value>\n\t\t</hsv>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/03A224/early_summer_leaves]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/03A224/100/100/early_summer_leaves.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/9990/9990224_early_summer_leaves.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/03A224</apiUrl>\n\t</color>\n\t<color>\n\t\t<id>9990223</id>\n\t\t<title><![CDATA[late summer leaves]]></title>\n\t\t<userName><![CDATA[driver22]]></userName>\n\t\t<numViews>0</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-29 23:16:25</dateCreated>\n\t\t<hex>426002</hex>\n\t\t<rgb>\n\t\t\t<red>66</red>\n\t\t\t<green>96</green>\n\t\t\t<blue>2</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>79</hue>\n\t\t\t<saturation>98</saturation>\n\t\t\t<value>38</value>\n\t\t</hsv>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/426002/late_summer_leaves]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/426002/100/100/late_summer_leaves.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/9990/9990223_late_summer_leaves.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/426002</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556597858, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000037, 
    connect = 0.885792, pretransfer = 0.886041, starttransfer = 1.079068, 
    total = 1.079194)), class = "response")
