structure(list(url = "http://www.colourlovers.com/api/colors/random?format=xml&lover=junk", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 03:55:43 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "857", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 03:55:43 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "857", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"9990216\">\n\t<color>\n\t\t<id>8348579</id>\n\t\t<title><![CDATA[ouch]]></title>\n\t\t<userName><![CDATA[ppkmd]]></userName>\n\t\t<numViews>10</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2015-12-30 10:37:57</dateCreated>\n\t\t<hex>A06259</hex>\n\t\t<rgb>\n\t\t\t<red>160</red>\n\t\t\t<green>98</green>\n\t\t\t<blue>89</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>8</hue>\n\t\t\t<saturation>44</saturation>\n\t\t\t<value>63</value>\n\t\t</hsv>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/color/69636F/Store_me_Storm\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2618/2618826i.jpg\" /></a><a href=\"http://www.colourlovers.com/color/A79DA9/Not_Flying_Elephant\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2620/2620182i.jpg\" /></a>\r\n<div style=\"max-width: 400px ;margin-left: auto; margin-right: auto; text-align: center; color:#ebf2f5; border: 4px dotted #6b6b6b; font-size:112%; font-family:palatino linotype, palatino, serif; line-height:1.5; padding:12px; background-color: #1b1b1f; background-image: -moz-linear-gradient(top, #1b1b1f, #31314a); background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #1b1b1f),color-stop(1, #31314a)); filter: progid:DXImageTransform.Microsoft.gradient(startColorStr=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/A06259/ouch]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/A06259/100/100/ouch.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/8348/8348579_ouch.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/A06259</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556596543, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000037, 
    connect = 0.320413, pretransfer = 0.320528, starttransfer = 1.13917, 
    total = 1.139339)), class = "response")
