structure(list(url = "http://www.colourlovers.com/api/colors/random?format=xml&lover=junk", 
    status_code = 200L, headers = structure(list(date = "Mon, 29 Apr 2019 16:50:53 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "870", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Mon, 29 Apr 2019 16:50:53 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "870", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"9989987\">\n\t<color>\n\t\t<id>9772986</id>\n\t\t<title><![CDATA[watery]]></title>\n\t\t<userName><![CDATA[COLOURlover]]></userName>\n\t\t<numViews>144</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>3</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2017-03-01 12:45:03</dateCreated>\n\t\t<hex>6BA0D7</hex>\n\t\t<rgb>\n\t\t\t<red>107</red>\n\t\t\t<green>160</green>\n\t\t\t<blue>215</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>211</hue>\n\t\t\t<saturation>50</saturation>\n\t\t\t<value>84</value>\n\t\t</hsv>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/color/69636F/Store_me_Storm\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2618/2618826i.jpg\" /></a><a href=\"http://www.colourlovers.com/color/A79DA9/Not_Flying_Elephant\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2620/2620182i.jpg\" /></a>\r\n<div style=\"max-width: 400px ;margin-left: auto; margin-right: auto; text-align: center; color:#ebf2f5; border: 4px dotted #6b6b6b; font-size:112%; font-family:palatino linotype, palatino, serif; line-height:1.5; padding:12px; background-color: #1b1b1f; background-image: -moz-linear-gradient(top, #1b1b1f, #31314a); background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #1b1b1f),color-stop(1, #31314a)); filter: progid:DXImageTransform.Microsoft.gradient(startColorStr=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/6BA0D7/watery]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/6BA0D7/100/100/watery.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/9772/9772986_watery.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/6BA0D7</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556556653, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.002435, 
    connect = 0.268424, pretransfer = 0.268624, starttransfer = 0.473492, 
    total = 0.473596)), class = "response")
