structure(list(url = "http://www.colourlovers.com/api/colors/random?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 03:55:36 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "862", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 03:55:36 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "862", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"9990216\">\n\t<color>\n\t\t<id>8712662</id>\n\t\t<title><![CDATA[2D969D]]></title>\n\t\t<userName><![CDATA[KatherineT]]></userName>\n\t\t<numViews>1</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2016-03-29 18:26:58</dateCreated>\n\t\t<hex>2D969D</hex>\n\t\t<rgb>\n\t\t\t<red>45</red>\n\t\t\t<green>150</green>\n\t\t\t<blue>157</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>184</hue>\n\t\t\t<saturation>71</saturation>\n\t\t\t<value>62</value>\n\t\t</hsv>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/color/69636F/Store_me_Storm\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2618/2618826i.jpg\" /></a><a href=\"http://www.colourlovers.com/color/A79DA9/Not_Flying_Elephant\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2620/2620182i.jpg\" /></a>\r\n<div style=\"max-width: 400px ;margin-left: auto; margin-right: auto; text-align: center; color:#ebf2f5; border: 4px dotted #6b6b6b; font-size:112%; font-family:palatino linotype, palatino, serif; line-height:1.5; padding:12px; background-color: #1b1b1f; background-image: -moz-linear-gradient(top, #1b1b1f, #31314a); background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #1b1b1f),color-stop(1, #31314a)); filter: progid:DXImageTransform.Microsoft.gradient(startColorStr=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/2D969D/2D969D]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/2D969D/100/100/2D969D.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/8712/8712662_2D969D.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/2D969D</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556596536, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.002837, 
    connect = 0.151792, pretransfer = 0.151958, starttransfer = 0.331047, 
    total = 0.331124)), class = "response")
