structure(list(url = "http://www.colourlovers.com/api/colors/top?format=xml&lover=Skyblue2u&numResults=1", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 19:27:52 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "875", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 19:27:52 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "875", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"1000\">\n\t<color>\n\t\t<id>1086335</id>\n\t\t<title><![CDATA[dutch teal]]></title>\n\t\t<userName><![CDATA[Skyblue2u]]></userName>\n\t\t<numViews>56010</numViews>\n\t\t<numVotes>1105</numVotes>\n\t\t<numComments>49</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>3</rank>\n\t\t<dateCreated>2008-05-19 17:31:06</dateCreated>\n\t\t<hex>1693A5</hex>\n\t\t<rgb>\n\t\t\t<red>22</red>\n\t\t\t<green>147</green>\n\t\t\t<blue>165</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>188</hue>\n\t\t\t<saturation>87</saturation>\n\t\t\t<value>65</value>\n\t\t</hsv>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/color/69636F/Store_me_Storm\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2618/2618826i.jpg\" /></a><a href=\"http://www.colourlovers.com/color/A79DA9/Not_Flying_Elephant\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2620/2620182i.jpg\" /></a>\r\n<div style=\"max-width: 400px ;margin-left: auto; margin-right: auto; text-align: center; color:#ebf2f5; border: 4px dotted #6b6b6b; font-size:112%; font-family:palatino linotype, palatino, serif; line-height:1.5; padding:12px; background-color: #1b1b1f; background-image: -moz-linear-gradient(top, #1b1b1f, #31314a); background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #1b1b1f),color-stop(1, #31314a)); filter: progid:DXImageTransform.Microsoft.gradient(startColorStr=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/1693A5/dutch_teal]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/1693A5/100/100/dutch_teal.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/1086/1086335_dutch_teal.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/1693A5</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556652472, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.7e-05, 
    connect = 0.124364, pretransfer = 0.124458, starttransfer = 0.340365, 
    total = 0.340425)), class = "response")
