structure(list(url = "http://www.colourlovers.com/api/patterns/new?format=xml&numResults=1", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:33:47 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "535", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:33:47 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "535", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<patterns numResults=\"1\" totalResults=\"1000\">\n\t<pattern>\n\t\t<id>5794419</id>\n\t\t<title><![CDATA[Blue Royale3]]></title>\n\t\t<userName><![CDATA[artystyc]]></userName>\n\t\t<numViews>28</numViews>\n\t\t<numVotes>5</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-30 00:22:03</dateCreated>\n\t\t<colors>\n\t\t\t<hex>68BBF7</hex>\n\t\t\t<hex>F295FC</hex>\n\t\t\t<hex>9703AC</hex>\n\t\t\t<hex>0541F7</hex>\n\t\t\t<hex>02084C</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/pattern/5794419/Blue_Royale3]]></url>\n\t\t<imageUrl><![CDATA[http://static.colourlovers.com/images/patterns/5794/5794419.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/n/5794/5794419_Blue_Royale3.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/pattern/5794419</apiUrl>\n\t\t<template>\n\t\t\t<title><![CDATA[( Take it Back )]]></title>\n\t\t\t<url><![CDATA[http://www.colourlovers.com/pattern/template/418691/(_Take_it_Back_)]]></url>\n\t\t\t<author>\n\t\t\t\t<userName><![CDATA[praxicalidocious]]></userName>\n\t\t\t\t<url><![CDATA[http://www.colourlovers.com/lover/praxicalidocious]]></url>\n\t\t\t</author>\n\t\t</template>\n\t</pattern>\n</patterns>"), 
    date = structure(1556645627, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000034, 
    connect = 0.123194, pretransfer = 0.123265, starttransfer = 0.259954, 
    total = 0.260041)), class = "response")
