structure(list(url = "http://www.colourlovers.com/api/patterns/new?format=xml&numResults=1&hex=574333,F1F79C,F7F4BC,E6BD87,7A9157", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:33:48 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "507", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:33:48 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "507", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<patterns numResults=\"1\" totalResults=\"1\">\n\t<pattern>\n\t\t<id>5792540</id>\n\t\t<title><![CDATA[AOMM]]></title>\n\t\t<userName><![CDATA[Mario Matthar]]></userName>\n\t\t<numViews>8</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-23 20:23:19</dateCreated>\n\t\t<colors>\n\t\t\t<hex>574333</hex>\n\t\t\t<hex>F1F79C</hex>\n\t\t\t<hex>F7F4BC</hex>\n\t\t\t<hex>E6BD87</hex>\n\t\t\t<hex>7A9157</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/pattern/5792540/AOMM]]></url>\n\t\t<imageUrl><![CDATA[http://static.colourlovers.com/images/patterns/5792/5792540.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/n/5792/5792540_AOMM.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/pattern/5792540</apiUrl>\n\t\t<template>\n\t\t\t<title><![CDATA[Ornaturalist]]></title>\n\t\t\t<url><![CDATA[http://www.colourlovers.com/pattern/template/526738/Ornaturalist]]></url>\n\t\t\t<author>\n\t\t\t\t<userName><![CDATA[eighteyed]]></userName>\n\t\t\t\t<url><![CDATA[http://www.colourlovers.com/lover/eighteyed]]></url>\n\t\t\t</author>\n\t\t</template>\n\t</pattern>\n</patterns>"), 
    date = structure(1556645628, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000033, 
    connect = 0.123818, pretransfer = 0.123914, starttransfer = 0.562431, 
    total = 0.562495)), class = "response")
