structure(list(url = "http://www.colourlovers.com/api/patterns/random?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:33:36 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "763", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:33:36 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "763", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<patterns numResults=\"1\" totalResults=\"5794619\">\n\t<pattern>\n\t\t<id>1123657</id>\n\t\t<title><![CDATA[Linear]]></title>\n\t\t<userName><![CDATA[UPtimist]]></userName>\n\t\t<numViews>10</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2010-11-01 12:00:01</dateCreated>\n\t\t<colors>\n\t\t\t<hex>E8DA00</hex>\n\t\t\t<hex>1A00CD</hex>\n\t\t\t<hex>00A891</hex>\n\t\t\t<hex>000000</hex>\n\t\t\t<hex>000000</hex>\n\t\t</colors>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/palette/2285499/Nestled\" target=\"_blank\"><img src=\"http://www.colourlovers.com/images/badges/pw/2285/2285499_Nestled.png\" style=\"width: 240px; height: 120px; border: 0 none;\" alt=\"Nestled\" /></a>\r\n<div style=\"width: 300px; text-align: center;\"><a href=\"http://www.colourlovers.com/contests/moo/minicard/2285499\" target=\"_blank\" style=\"display: block; margin-bottom: 5px; width: 300px; height: 120px; -moz-box-shadow: 0 1px 4px #d1d1d1; -webkit-box-shadow: 0 1px 4px #d1d1d1; box-shadow: 0 1px 4px #d1d1d1; filter: progid:DXImageTransform.Microsoft.Shadow(Strength=1, Direction=180, Color=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/pattern/1123657/Linear]]></url>\n\t\t<imageUrl><![CDATA[http://static.colourlovers.com/images/patterns/1123/1123657.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/n/1123/1123657_Linear.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/pattern/1123657</apiUrl>\n\t\t<template>\n\t\t\t<title><![CDATA[Linear]]></title>\n\t\t\t<url><![CDATA[http://www.colourlovers.com/pattern/template/36664/Linear]]></url>\n\t\t\t<author>\n\t\t\t\t<userName><![CDATA[UPtimist]]></userName>\n\t\t\t\t<url><![CDATA[http://www.colourlovers.com/lover/UPtimist]]></url>\n\t\t\t</author>\n\t\t</template>\n\t</pattern>\n</patterns>"), 
    date = structure(1556645616, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000026, 
    connect = 0.125125, pretransfer = 0.125212, starttransfer = 0.335817, 
    total = 0.335968)), class = "response")
