structure(list(url = "http://www.colourlovers.com/api/patterns/top?format=xml&lover=Skyblue2u&numResults=1", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 20:26:34 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "638", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 20:26:34 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "638", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<patterns numResults=\"1\" totalResults=\"1000\">\n\t<pattern>\n\t\t<id>328710</id>\n\t\t<title><![CDATA[Seldom Dared Dream]]></title>\n\t\t<userName><![CDATA[Skyblue2u]]></userName>\n\t\t<numViews>44640</numViews>\n\t\t<numVotes>1978</numVotes>\n\t\t<numComments>104</numComments>\n\t\t<numHearts>5</numHearts>\n\t\t<rank>9</rank>\n\t\t<dateCreated>2009-01-02 15:43:00</dateCreated>\n\t\t<colors>\n\t\t\t<hex>BBC793</hex>\n\t\t\t<hex>77CCA4</hex>\n\t\t\t<hex>827551</hex>\n\t\t\t<hex>F1EEC5</hex>\n\t\t\t<hex>FECC99</hex>\n\t\t</colors>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/palette/1217510/Updated_Recipe?widths=1\"><img src=\"http://www.colourlovers.com/images/badges/pw/1217/1217510_Updated_Recipe.png\" style=\"width:240px;height:120px;border:0 none;\" alt=\"Updated_Recipe\" /></a>]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/pattern/328710/Seldom_Dared_Dream]]></url>\n\t\t<imageUrl><![CDATA[http://static.colourlovers.com/images/patterns/328/328710.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/n/328/328710_Seldom_Dared_Dream.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/pattern/328710</apiUrl>\n\t\t<template>\n\t\t\t<title><![CDATA[Pattern 16]]></title>\n\t\t\t<url><![CDATA[http://www.colourlovers.com/pattern/template/16/Pattern_16]]></url>\n\t\t\t<author>\n\t\t\t\t<userName><![CDATA[COLOURlover]]></userName>\n\t\t\t\t<url><![CDATA[http://www.colourlovers.com/lover/COLOURlover]]></url>\n\t\t\t</author>\n\t\t</template>\n\t</pattern>\n</patterns>"), 
    date = structure(1556655994, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.2e-05, 
    connect = 0.124049, pretransfer = 0.124178, starttransfer = 0.323743, 
    total = 0.32384)), class = "response")
