structure(list(url = "http://www.colourlovers.com/api/lover/COLOURlovers?format=xml&comments=0", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 18:27:52 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "343", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 18:27:52 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "343", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<lovers numResults=\"1\" totalResults=\"8816007\">\n\t<lover>\n\t\t<userName><![CDATA[colourlovers]]></userName>\n\t\t<dateRegistered>2007-09-11 02:44:32</dateRegistered>\n\t\t<dateLastActive>2011-07-21 12:26:10</dateLastActive>\n\t\t<rating>0</rating>\n\t\t<location><![CDATA[]]></location>\n\t\t<numColors>0</numColors>\n\t\t<numPalettes>0</numPalettes>\n\t\t<numPatterns>0</numPatterns>\n\t\t<numCommentsMade>0</numCommentsMade>\n\t\t<numLovers>0</numLovers>\n\t\t<numCommentsOnProfile>0</numCommentsOnProfile>\n\t\t<url><![CDATA[http://www.colourlovers.com/lover/colourlovers]]></url>\n\t\t<apiUrl><![CDATA[http://www.colourlovers.com/api/lover/colourlovers]]></apiUrl>\n\t</lover>\n</lovers>"), 
    date = structure(1556648872, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000021, 
    connect = 0.122422, pretransfer = 0.122524, starttransfer = 0.261297, 
    total = 0.261368)), class = "response")
