structure(list(url = "http://www.colourlovers.com/api/palette/113451?format=xml&widths=0", 
    status_code = 200L, headers = structure(list(date = "Sun, 28 Apr 2019 05:07:38 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "667", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sun, 28 Apr 2019 05:07:38 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "667", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"1\" totalResults=\"4643345\">\n\t<palette>\n\t\t<id>113451</id>\n\t\t<title><![CDATA[Anaconda]]></title>\n\t\t<userName><![CDATA[kunteper]]></userName>\n\t\t<numViews>663</numViews>\n\t\t<numVotes>2</numVotes>\n\t\t<numComments>2</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2007-08-05 14:14:15</dateCreated>\n\t\t<colors>\n\t\t\t<hex>2B2D42</hex>\n\t\t\t<hex>7A7D7F</hex>\n\t\t\t<hex>B1BBCF</hex>\n\t\t\t<hex>6E0B21</hex>\n\t\t\t<hex>9B4D73</hex>\n\t\t</colors>\n\t\t<description><![CDATA[I-MOO\r\n<div style=\"width: 300px; text-align: center;\"><a href=\"http://www.colourlovers.com/contests/moo/minicard/2291466\" target=\"_blank\" style=\"display: block; margin-bottom: 5px; width: 300px; height: 120px; -moz-box-shadow: 0 1px 4px #d1d1d1; -webkit-box-shadow: 0 1px 4px #d1d1d1; box-shadow: 0 1px 4px #d1d1d1; filter: progid:DXImageTransform.Microsoft.Shadow(Strength=1, Direction=180, Color=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/113451/Anaconda]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/2B2D42/7A7D7F/B1BBCF/6E0B21/9B4D73/Anaconda.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/p/113/113451_Anaconda.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/113451</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556428058, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000028, 
    connect = 0.154294, pretransfer = 0.154415, starttransfer = 0.350205, 
    total = 0.350558)), class = "response")
