structure(list(url = "http://www.colourlovers.com/api/palette/4643793?format=xml&widths=0", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 20:18:04 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "425", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 20:18:04 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "425", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"1\" totalResults=\"4643793\">\n\t<palette>\n\t\t<id>4643793</id>\n\t\t<title><![CDATA[ath palette 2]]></title>\n\t\t<userName><![CDATA[andrewheiss]]></userName>\n\t\t<numViews>4</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-30 15:13:20</dateCreated>\n\t\t<colors>\n\t\t\t<hex>9688A6</hex>\n\t\t\t<hex>E49924</hex>\n\t\t\t<hex>49AD60</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4643793/ath_palette_2]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/9688A6/E49924/49AD60/ath_palette_2.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/pw/4643/4643793_ath_palette_2.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4643793</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556655484, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000024, 
    connect = 0.124495, pretransfer = 0.124621, starttransfer = 0.290056, 
    total = 0.290193)), class = "response")
