structure(list(url = "http://www.colourlovers.com/api/palette/4643751?format=xml&widths=0", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 16:21:23 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "509", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 16:21:23 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "509", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"1\" totalResults=\"4643751\">\n\t<palette>\n\t\t<id>4643751</id>\n\t\t<title><![CDATA[Progress Two]]></title>\n\t\t<userName><![CDATA[cherylcolan]]></userName>\n\t\t<numViews>10</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-30 11:12:50</dateCreated>\n\t\t<colors>\n\t\t\t<hex>FFD9AA</hex>\n\t\t\t<hex>FFB255</hex>\n\t\t\t<hex>FF8C00</hex>\n\t\t\t<hex>5F8CA3</hex>\n\t\t\t<hex>376F8C</hex>\n\t\t</colors>\n\t\t<description><![CDATA[Working on a palette for graphing progress with 3 colors that represent not meeting proficiency, two colors meeting proficiency.]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4643751/Progress_Two]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/FFD9AA/FFB255/FF8C00/5F8CA3/376F8C/Progress_Two.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/p/4643/4643751_Progress_Two.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4643751</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556641283, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000055, 
    connect = 0.168195, pretransfer = 0.16833, starttransfer = 0.37279, 
    total = 0.372892)), class = "response")
