structure(list(url = "http://www.colourlovers.com/api/lovers/new?format=xml&numResults=1", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 18:27:49 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "339", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 18:27:49 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "339", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<lovers numResults=\"1\" totalResults=\"8816007\">\n\t<lover>\n\t\t<userName><![CDATA[h1qofmn626]]></userName>\n\t\t<dateRegistered>2019-04-30 13:26:57</dateRegistered>\n\t\t<dateLastActive>2019-04-30 13:27:42</dateLastActive>\n\t\t<rating>0</rating>\n\t\t<location><![CDATA[]]></location>\n\t\t<numColors>0</numColors>\n\t\t<numPalettes>0</numPalettes>\n\t\t<numPatterns>0</numPatterns>\n\t\t<numCommentsMade>0</numCommentsMade>\n\t\t<numLovers>0</numLovers>\n\t\t<numCommentsOnProfile>0</numCommentsOnProfile>\n\t\t<url><![CDATA[http://www.colourlovers.com/lover/h1qofmn626]]></url>\n\t\t<apiUrl><![CDATA[http://www.colourlovers.com/api/lover/h1qofmn626]]></apiUrl>\n\t</lover>\n</lovers>"), 
    date = structure(1556648869, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000017, 
    connect = 0.124079, pretransfer = 0.124154, starttransfer = 0.458513, 
    total = 0.458593)), class = "response")
