structure(list(url = "http://www.colourlovers.com/api/color/6B4106?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Sun, 28 Apr 2019 05:07:32 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "872", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sun, 28 Apr 2019 05:07:32 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "872", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"9989248\">\n\t<color>\n\t\t<id>903893</id>\n\t\t<title><![CDATA[wet dirt]]></title>\n\t\t<userName><![CDATA[jessicabrown]]></userName>\n\t\t<numViews>557</numViews>\n\t\t<numVotes>1</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2008-03-17 11:22:21</dateCreated>\n\t\t<hex>6B4106</hex>\n\t\t<rgb>\n\t\t\t<red>107</red>\n\t\t\t<green>65</green>\n\t\t\t<blue>6</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>35</hue>\n\t\t\t<saturation>94</saturation>\n\t\t\t<value>42</value>\n\t\t</hsv>\n\t\t<description><![CDATA[<a href=\"http://www.colourlovers.com/color/69636F/Store_me_Storm\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2618/2618826i.jpg\" /></a><a href=\"http://www.colourlovers.com/color/A79DA9/Not_Flying_Elephant\" target=\"_blank\"><img src=\"http://static.colourlovers.com/images/colors/2620/2620182i.jpg\" /></a>\r\n<div style=\"max-width: 400px ;margin-left: auto; margin-right: auto; text-align: center; color:#ebf2f5; border: 4px dotted #6b6b6b; font-size:112%; font-family:palatino linotype, palatino, serif; line-height:1.5; padding:12px; background-color: #1b1b1f; background-image: -moz-linear-gradient(top, #1b1b1f, #31314a); background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #1b1b1f),color-stop(1, #31314a)); filter: progid:DXImageTransform.Microsoft.gradient(startColorStr=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/6B4106/wet_dirt]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/6B4106/100/100/wet_dirt.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/903/903893_wet_dirt.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/6B4106</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556428052, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000029, 
    connect = 0.150118, pretransfer = 0.150249, starttransfer = 0.340385, 
    total = 0.340546)), class = "response")
