structure(list(url = "http://www.colourlovers.com/api/color/f06134?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 04:12:32 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "461", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 04:12:32 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "461", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<colors numResults=\"1\" totalResults=\"9990220\">\n\t<color>\n\t\t<id>9987886</id>\n\t\t<title><![CDATA[3]]></title>\n\t\t<userName><![CDATA[ninapetrov]]></userName>\n\t\t<numViews>1</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-23 15:57:22</dateCreated>\n\t\t<hex>F06134</hex>\n\t\t<rgb>\n\t\t\t<red>240</red>\n\t\t\t<green>97</green>\n\t\t\t<blue>52</blue>\n\t\t</rgb>\n\t\t<hsv>\n\t\t\t<hue>14</hue>\n\t\t\t<saturation>78</saturation>\n\t\t\t<value>94</value>\n\t\t</hsv>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/color/F06134/3]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/img/F06134/100/100/3.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/c/9987/9987886_3.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/color/F06134</apiUrl>\n\t</color>\n</colors>"), 
    date = structure(1556597552, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000026, 
    connect = 0.14828, pretransfer = 0.148343, starttransfer = 0.331292, 
    total = 0.331353)), class = "response")
