structure(list(url = "http://www.colourlovers.com/api/palettes/new?format=xml&hueOption=red&numResults=2", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:10:10 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "562", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:10:10 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "562", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"2\" totalResults=\"1000\">\n\t<palette>\n\t\t<id>4643630</id>\n\t\t<title><![CDATA[{summerhood}]]></title>\n\t\t<userName><![CDATA[sparrowandcompass]]></userName>\n\t\t<numViews>29</numViews>\n\t\t<numVotes>2</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-29 15:58:51</dateCreated>\n\t\t<colors>\n\t\t\t<hex>FFD8D7</hex>\n\t\t\t<hex>D67882</hex>\n\t\t\t<hex>AD172C</hex>\n\t\t\t<hex>D5714D</hex>\n\t\t\t<hex>FCCB6E</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4643630/{summerhood}]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/FFD8D7/D67882/AD172C/D5714D/FCCB6E/{summerhood}.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/pw/4643/4643630_{summerhood}.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4643630</apiUrl>\n\t</palette>\n\t<palette>\n\t\t<id>4643621</id>\n\t\t<title><![CDATA[{sweetheart}]]></title>\n\t\t<userName><![CDATA[sparrowandcompass]]></userName>\n\t\t<numViews>23</numViews>\n\t\t<numVotes>1</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-29 15:33:25</dateCreated>\n\t\t<colors>\n\t\t\t<hex>8D2F47</hex>\n\t\t\t<hex>A96066</hex>\n\t\t\t<hex>C69185</hex>\n\t\t\t<hex>E2C1A3</hex>\n\t\t\t<hex>FEF2C2</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4643621/{sweetheart}]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/8D2F47/A96066/C69185/E2C1A3/FEF2C2/{sweetheart}.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/pw/4643/4643621_{sweetheart}.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4643621</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556644210, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000038, 
    connect = 0.12414, pretransfer = 0.124334, starttransfer = 0.259312, 
    total = 0.259362)), class = "response")
