structure(list(url = "http://www.colourlovers.com/api/palettes/new?format=xml&hueOption=yellow,orange&numResults=2", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:10:10 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "576", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:10:10 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "576", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"2\" totalResults=\"1000\">\n\t<palette>\n\t\t<id>4643222</id>\n\t\t<title><![CDATA[hottest]]></title>\n\t\t<userName><![CDATA[palalula]]></userName>\n\t\t<numViews>12</numViews>\n\t\t<numVotes>1</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-27 06:29:56</dateCreated>\n\t\t<colors>\n\t\t\t<hex>FC3C11</hex>\n\t\t\t<hex>BFB826</hex>\n\t\t\t<hex>DED637</hex>\n\t\t\t<hex>C4600E</hex>\n\t\t\t<hex>F26D00</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4643222/hottest]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/FC3C11/BFB826/DED637/C4600E/F26D00/hottest.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/p/4643/4643222_hottest.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4643222</apiUrl>\n\t</palette>\n\t<palette>\n\t\t<id>4642811</id>\n\t\t<title><![CDATA[Ride the rails]]></title>\n\t\t<userName><![CDATA[NatureDesigns]]></userName>\n\t\t<numViews>43</numViews>\n\t\t<numVotes>3</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-24 21:06:48</dateCreated>\n\t\t<colors>\n\t\t\t<hex>9D9959</hex>\n\t\t\t<hex>F62F28</hex>\n\t\t\t<hex>E4B080</hex>\n\t\t\t<hex>AF7E3B</hex>\n\t\t\t<hex>280F00</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4642811/Ride_the_rails]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/9D9959/F62F28/E4B080/AF7E3B/280F00/Ride_the_rails.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/pw/4642/4642811_Ride_the_rails.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4642811</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556644210, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.003011, 
    connect = 0.140239, pretransfer = 0.14031, starttransfer = 0.288017, 
    total = 0.288069)), class = "response")
