structure(list(url = "http://www.colourlovers.com/api/palettes/new?format=xml&numResults=1&hex=E8B3A2,E78BA4,5BA0B5,348246,264F18", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 17:10:14 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "450", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 17:10:14 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "450", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"1\" totalResults=\"1\">\n\t<palette>\n\t\t<id>4643620</id>\n\t\t<title><![CDATA[{motion}]]></title>\n\t\t<userName><![CDATA[sparrowandcompass]]></userName>\n\t\t<numViews>25</numViews>\n\t\t<numVotes>1</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-29 15:29:47</dateCreated>\n\t\t<colors>\n\t\t\t<hex>E8B3A2</hex>\n\t\t\t<hex>E78BA4</hex>\n\t\t\t<hex>5BA0B5</hex>\n\t\t\t<hex>348246</hex>\n\t\t\t<hex>264F18</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4643620/{motion}]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/E8B3A2/E78BA4/5BA0B5/348246/264F18/{motion}.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/pw/4643/4643620_{motion}.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4643620</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556644214, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000033, 
    connect = 0.124068, pretransfer = 0.124211, starttransfer = 0.478308, 
    total = 0.478363)), class = "response")
