structure(list(url = "http://www.colourlovers.com/api/palettes/new?format=xml&numResults=1", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 16:21:20 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "457", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 16:21:20 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "457", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"1\" totalResults=\"1000\">\n\t<palette>\n\t\t<id>4643639</id>\n\t\t<title><![CDATA[Tree at the End]]></title>\n\t\t<userName><![CDATA[Aldabrachelys]]></userName>\n\t\t<numViews>38</numViews>\n\t\t<numVotes>0</numVotes>\n\t\t<numComments>0</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2019-04-29 16:54:08</dateCreated>\n\t\t<colors>\n\t\t\t<hex>AA9E61</hex>\n\t\t\t<hex>945547</hex>\n\t\t\t<hex>632A27</hex>\n\t\t\t<hex>49352A</hex>\n\t\t\t<hex>5F7457</hex>\n\t\t</colors>\n\t\t<description><![CDATA[]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/4643639/Tree_at_the_End]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/AA9E61/945547/632A27/49352A/5F7457/Tree_at_the_End.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/p/4643/4643639_Tree_at_the_End.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/4643639</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556641280, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000028, 
    connect = 0.166782, pretransfer = 0.166959, starttransfer = 0.370832, 
    total = 0.370912)), class = "response")
