structure(list(url = "http://www.colourlovers.com/api/palettes/random?format=xml&", 
    status_code = 200L, headers = structure(list(date = "Tue, 30 Apr 2019 16:21:11 GMT", 
        server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "684", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 30 Apr 2019 16:21:11 GMT", 
            server = "Apache/2.2.22 (Ubuntu)", connection = "Close", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "684", `content-type` = "text/xml; charset=utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<palettes numResults=\"1\" totalResults=\"4643751\">\n\t<palette>\n\t\t<id>3004618</id>\n\t\t<title><![CDATA[madsknutson CLAD]]></title>\n\t\t<userName><![CDATA[syork]]></userName>\n\t\t<numViews>116</numViews>\n\t\t<numVotes>21</numVotes>\n\t\t<numComments>1</numComments>\n\t\t<numHearts>0</numHearts>\n\t\t<rank>0</rank>\n\t\t<dateCreated>2013-08-22 14:55:24</dateCreated>\n\t\t<colors>\n\t\t\t<hex>C1EF77</hex>\n\t\t\t<hex>83D586</hex>\n\t\t\t<hex>0D7C87</hex>\n\t\t\t<hex>151E55</hex>\n\t\t\t<hex>9B195F</hex>\n\t\t</colors>\n\t\t<description><![CDATA[I-MOO\r\n<div style=\"width: 300px; text-align: center;\"><a href=\"http://www.colourlovers.com/contests/moo/minicard/2291466\" target=\"_blank\" style=\"display: block; margin-bottom: 5px; width: 300px; height: 120px; -moz-box-shadow: 0 1px 4px #d1d1d1; -webkit-box-shadow: 0 1px 4px #d1d1d1; box-shadow: 0 1px 4px #d1d1d1; filter: progid:DXImageTransform.Microsoft.Shadow(Strength=1, Direction=180, Color=]]></description>\n\t\t<url><![CDATA[http://www.colourlovers.com/palette/3004618/madsknutson_CLAD]]></url>\n\t\t<imageUrl><![CDATA[http://www.colourlovers.com/paletteImg/C1EF77/83D586/0D7C87/151E55/9B195F/madsknutson_CLAD.png]]></imageUrl>\n\t\t<badgeUrl><![CDATA[http://www.colourlovers.com/images/badges/pw/3004/3004618_madsknutson_CLAD.png]]></badgeUrl>\n\t\t<apiUrl>http://www.colourlovers.com/api/palette/3004618</apiUrl>\n\t</palette>\n</palettes>"), 
    date = structure(1556641271, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000024, 
    connect = 0.232172, pretransfer = 0.232284, starttransfer = 0.419403, 
    total = 0.419544)), class = "response")
